//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgosyModel
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    [Serializable]
    public partial class ESM_COMP_USERS
    {
        public ESM_COMP_USERS()
        {
            /*
            this.ESM_USERGROUP = new HashSet<ESM_USERGROUP>();
            this.ESM_USERGROUP1 = new HashSet<ESM_USERGROUP>();
            this.ESM_PART_BUYER_GROUP_USER = new HashSet<ESM_PART_BUYER_GROUP_USER>();
            this.ESM_PROMOTIONAL_GIVEAWAY = new HashSet<ESM_PROMOTIONAL_GIVEAWAY>();
            this.ESM_SHIP_ESTIMATE = new HashSet<ESM_SHIP_ESTIMATE>();
            this.ESM_PROJECTS = new HashSet<ESM_PROJECTS>();
            this.ESM_PASS_HISTORY = new HashSet<ESM_PASS_HISTORY>();
            this.ESM_PASS_HISTORY1 = new HashSet<ESM_PASS_HISTORY>();
            this.ESM_REPNEW_VIEWS = new HashSet<ESM_REPNEW_VIEWS>();
            this.ESM_CONSUMER = new HashSet<ESM_CONSUMER>();
            this.ESM_RET_STORE_SIGN_PACK = new HashSet<ESM_RET_STORE_SIGN_PACK>();
            this.ESM_RET_VERSION_SIGNATURE_APPROVAL = new HashSet<ESM_RET_VERSION_SIGNATURE_APPROVAL>();
            this.ESM_RET_VERSION_SIGNATURE_APPROVAL1 = new HashSet<ESM_RET_VERSION_SIGNATURE_APPROVAL>();
            this.ASSET_ORDER = new HashSet<ASSET_ORDER>();
            this.ESM_RET_APPROVAL_EMAIL = new HashSet<ESM_RET_APPROVAL_EMAIL>();
            this.ESM_RET_APPROVAL_EMAIL1 = new HashSet<ESM_RET_APPROVAL_EMAIL>();
            this.ESM_RET_USER_MAP = new HashSet<ESM_RET_USER_MAP>();
            this.SYS_TASK = new HashSet<SYS_TASK>();
            this.SYS_TASK_ORDER_IMPORT = new HashSet<SYS_TASK_ORDER_IMPORT>();
            this.ESM_RET_VERSION = new HashSet<ESM_RET_VERSION>();
            this.ESM_PURCHASE_ORDERS = new HashSet<ESM_PURCHASE_ORDERS>();
            this.ESM_LOGIN_AUDIT = new HashSet<ESM_LOGIN_AUDIT>();
            this.ESM_LOGIN_TOKEN = new HashSet<ESM_LOGIN_TOKEN>();
            this.ESM_APPROVALS = new HashSet<ESM_APPROVALS>();
            this.ESM_PROJECT_REVISION_COMMENTS = new HashSet<ESM_PROJECT_REVISION_COMMENTS>();
            this.ESM_PROJECT_REVISIONS = new HashSet<ESM_PROJECT_REVISIONS>();
            this.ESM_PART_LIMIT = new HashSet<ESM_PART_LIMIT>();
            this.ESM_APPROVAL_ROUTING = new HashSet<ESM_APPROVAL_ROUTING>();
            this.ESM_ACCOUNTING_UNIT_APPROVAL = new HashSet<ESM_ACCOUNTING_UNIT_APPROVAL>();
            this.ESM_HD_COMMENTS = new HashSet<ESM_HD_COMMENTS>();
            this.ESM_HD_TICKET_DETAIL = new HashSet<ESM_HD_TICKET_DETAIL>();
            this.ESM_HD_TICKET_DETAIL1 = new HashSet<ESM_HD_TICKET_DETAIL>();
            this.ESM_HD_TICKET = new HashSet<ESM_HD_TICKET>();
            this.ESM_HD_TICKET1 = new HashSet<ESM_HD_TICKET>();
            this.ESM_HD_COMMENTS1 = new HashSet<ESM_HD_COMMENTS>();
            this.ESM_REP_SLICE_USER = new HashSet<ESM_REP_SLICE_USER>();
            this.ESM_HIERARCHY = new HashSet<ESM_HIERARCHY>();
            this.ESM_HIERARCHY1 = new HashSet<ESM_HIERARCHY>();
            this.ESM_MSGUSER = new HashSet<ESM_MSGUSER>();
            this.ESM_MESSAGES = new HashSet<ESM_MESSAGES>();
            this.ESM_MESSAGES1 = new HashSet<ESM_MESSAGES>();
            this.ASSETs = new HashSet<ASSET>();
            this.ESM_CART = new HashSet<ESM_CART>();
            this.ESM_CART_CUST_FIELDS = new HashSet<ESM_CART_CUST_FIELDS>();
            this.ESM_CART_QUICK = new HashSet<ESM_CART_QUICK>();
            this.ESM_ASSET_UPLOAD = new HashSet<ESM_ASSET_UPLOAD>();
            this.ESM_DASH = new HashSet<ESM_DASH>();
            this.ESM_DASH_WIDGET_USER = new HashSet<ESM_DASH_WIDGET_USER>();
            this.ESM_IMPORT_PROCESSING = new HashSet<ESM_IMPORT_PROCESSING>();
            this.ESM_ASSET_LIST = new HashSet<ESM_ASSET_LIST>();
            this.ESM_SOFT_PROOFING_TRANSACTION_LOG = new HashSet<ESM_SOFT_PROOFING_TRANSACTION_LOG>();
            this.ESM_GLOBAL_FORMS_USERS = new HashSet<ESM_GLOBAL_FORMS_USERS>();
            this.ESM_PROMO_USERS_USERGROUP = new HashSet<ESM_PROMO_USERS_USERGROUP>();
            this.ESM_COMP_USER_ADDRESS_MAP = new HashSet<ESM_COMP_USER_ADDRESS_MAP>();
            this.ESM_CART_ADDRESS = new HashSet<ESM_CART_ADDRESS>();
            this.ESM_ACCOUNTING_UNIT_USER = new HashSet<ESM_ACCOUNTING_UNIT_USER>();
            this.ESM_COMP_USER_PAGES = new HashSet<ESM_COMP_USER_PAGES>();
            this.ESM_FILE_DOWNLOAD_LOG = new HashSet<ESM_FILE_DOWNLOAD_LOG>();
            this.ESM_MAILING_LIST = new HashSet<ESM_MAILING_LIST>();
            this.ESM_COMP_USER_WORKFLOW = new HashSet<ESM_COMP_USER_WORKFLOW>();
            this.ESM_TRIGGER_RULE_APPROVER = new HashSet<ESM_TRIGGER_RULE_APPROVER>();
            this.ESM_ORDER_APPROVER_WORKFLOW = new HashSet<ESM_ORDER_APPROVER_WORKFLOW>();
            this.ESM_COMP_USER_DOLLAR = new HashSet<ESM_COMP_USER_DOLLAR>();
            this.ESM_COMP_USER_PAYMENT_METHOD = new HashSet<ESM_COMP_USER_PAYMENT_METHOD>();
            this.ESM_GLOBAL_FORMS_PROFILE = new HashSet<ESM_GLOBAL_FORMS_PROFILE>();
            this.ESM_ORDERS = new HashSet<ESM_ORDERS>();
            this.ESM_USER_FILES = new HashSet<ESM_USER_FILES>();
            this.ESM_REPNEW_VIEW_USERS = new HashSet<ESM_REPNEW_VIEW_USERS>();
            */
        }
        // primitiveProperties
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "COMP_USER_ID")]
        public int COMP_USER_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "COMPANY_ID")]
        public Nullable<int> COMPANY_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ADDRESS_ID")]
        [Obsolete("ADDRESS_ID should no longer be used in Argosy")]
        public Nullable<int> ADDRESS_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SITE_ID")]
        public Nullable<int> SITE_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "MULTIPLIER_ID")]
        [Obsolete("MULTIPLIER_ID should no longer be used in Argosy")]
        public Nullable<int> MULTIPLIER_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DEFAULT_SKIN_ID")]
        [Obsolete("DEFAULT_SKIN_ID should no longer be used in Argosy")]
        public Nullable<int> DEFAULT_SKIN_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "STYLE_SHEET_ID")]
        [Obsolete("STYLE_SHEET_ID should no longer be used in Argosy")]
        public int STYLE_SHEET_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "THEME_ID")]
        public Nullable<int> THEME_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "USERNAME")]
        public string USERNAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PASSWORD { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FIRST_NAME")]
        public string FIRST_NAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "LAST_NAME")]
        public string LAST_NAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "TITLE")]
        public string TITLE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "EMAIL")]
        public string EMAIL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "zPHONE")]
        [Obsolete("zPHONE should no longer be used in Argosy")]
        public Nullable<decimal> zPHONE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PHONE_NUMBER")]
        public string PHONE_NUMBER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "NAME")]
        public string NAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ADDRESS1")]
        public string ADDRESS1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ADDRESS2")]
        public string ADDRESS2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ADDRESS3")]
        public string ADDRESS3 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CITY")]
        public string CITY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "STATE")]
        public Nullable<int> STATE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "COUNTRY")]
        [Obsolete("COUNTRY should no longer be used in Argosy")]
        public string COUNTRY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ZIP")]
        public string ZIP { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SPENDING_LIMIT")]
        public decimal SPENDING_LIMIT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ACTIVE")]
        public string ACTIVE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ADMIN_ACCESS")]
        public string ADMIN_ACCESS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PROJECT_REVISION_ACCESS")]
        public string PROJECT_REVISION_ACCESS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "POWER_BUYER")]
        public string POWER_BUYER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "EMAIL_DISTR")]
        public string EMAIL_DISTR { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PRINT_ORDERS")]
        [Obsolete("PRINT_ORDERS should no longer be used in Argosy")]
        public string PRINT_ORDERS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "BILLING_ACCESS")]
        [Obsolete("BILLING_ACCESS should no longer be used in Argosy")]
        public string BILLING_ACCESS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DISCOUNT_LEVEL")]
        [Obsolete("DISCOUNT_LEVEL should no longer be used in Argosy")]
        public Nullable<int> DISCOUNT_LEVEL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DISCOUNT_DOLLARS")]
        [Obsolete("DISCOUNT_DOLLARS should no longer be used in Argosy")]
        public decimal DISCOUNT_DOLLARS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "REGISTER_DATE")]
        [Obsolete("REGISTER_DATE should no longer be used in Argosy")]
        public Nullable<System.DateTime> REGISTER_DATE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DEFAULT_LOGO")]
        public string DEFAULT_LOGO { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DIVISION_NAME")]
        public string DIVISION_NAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "WEBSITE")]
        public string WEBSITE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FAX")]
        public Nullable<decimal> FAX { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CUSTOM01")]
        public string CUSTOM01 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CUSTOM02")]
        public string CUSTOM02 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CUSTOM03")]
        public string CUSTOM03 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "EXT_IDENTIFIER")]
        public string EXT_IDENTIFIER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "USER_PROFILE_GROUP_ID")]
        public Nullable<int> USER_PROFILE_GROUP_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "COMP_USERGROUP_ID")]
        public Nullable<int> COMP_USERGROUP_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_RFQ_MODULE")]
        public string FLAG_RFQ_MODULE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_EMAIL_CREATE_MESSAGE")]
        public bool FLAG_EMAIL_CREATE_MESSAGE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_EMAIL_ORDER_PLACED")]
        public bool FLAG_EMAIL_ORDER_PLACED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_EMAIL_PROJECT_REVISION")]
        public bool FLAG_EMAIL_PROJECT_REVISION { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_EMAIL_ORDER_SHIPPED")]
        public bool FLAG_EMAIL_ORDER_SHIPPED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_EMAIL_INVENTORY_WARNING")]
        public bool FLAG_EMAIL_INVENTORY_WARNING { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_CONSUMER_MODULE")]
        [Obsolete("FLAG_CONSUMER_MODULE should no longer be used in Argosy")]
        public bool FLAG_CONSUMER_MODULE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_APPROVALS")]
        [Obsolete("FLAG_APPROVALS should no longer be used in Argosy")]
        public int FLAG_APPROVALS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_AGREED_TO_USRAGR")]
        [Obsolete("FLAG_AGREED_TO_USRAGR should no longer be used in Argosy")]
        public string FLAG_AGREED_TO_USRAGR { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_BULK_ORDER_PLACEMENT")]
        public bool FLAG_ALLOW_BULK_ORDER_PLACEMENT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_STORE")]
        public bool IS_STORE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_RETAIL")]
        public bool IS_RETAIL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "EMAIL_SENT")]
        public bool EMAIL_SENT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "USRAGR_DATE")]
        [Obsolete("USRAGR_DATE should no longer be used in Argosy")]
        public Nullable<System.DateTime> USRAGR_DATE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "USRAGR_IP")]
        [Obsolete("USRAGR_IP should no longer be used in Argosy")]
        public string USRAGR_IP { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "USRAGR_NAME")]
        [Obsolete("USRAGR_NAME should no longer be used in Argosy")]
        public string USRAGR_NAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "USRAGR_COMPANY")]
        [Obsolete("USRAGR_COMPANY should no longer be used in Argosy")]
        public string USRAGR_COMPANY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DATECREATED")]
        public Nullable<System.DateTime> DATECREATED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CREATEDBY")]
        public int CREATEDBY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DATEMODIFIED")]
        public Nullable<System.DateTime> DATEMODIFIED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "MODIFIEDBY")]
        public int MODIFIEDBY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ACCOUNTING_UNIT_ID")]
        [Obsolete("ACCOUNTING_UNIT_ID should no longer be used in Argosy")]
        public Nullable<int> ACCOUNTING_UNIT_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "TITLE2")]
        public string TITLE2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "USER_PHOTO")]
        public string USER_PHOTO { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PHONE_NUMBER2")]
        public string PHONE_NUMBER2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PHONE_NUMBER3")]
        public string PHONE_NUMBER3 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ASSET_ROLE_ID")]
        public Nullable<int> ASSET_ROLE_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "COMP_USER_GUID")]
        public System.Guid COMP_USER_GUID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_RETAIL_CONTRIBUTOR")]
        public Nullable<bool> IS_RETAIL_CONTRIBUTOR { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "COMP_USER_HASH")]
        public string COMP_USER_HASH { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "INCLUSION_TAGS")]
        public string INCLUSION_TAGS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "EXCLUSION_TAGS")]
        public string EXCLUSION_TAGS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "EXTERNAL_ID")]
        public string EXTERNAL_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_SSO")]
        public bool IS_SSO { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DYNAMIC_USERGROUP_ID")]
        public Nullable<int> DYNAMIC_USERGROUP_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_GENERIC_USER")]
        public bool IS_GENERIC_USER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_PRICE_ADMIN")]
        public bool IS_PRICE_ADMIN { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CC_EMAIL")]
        public string CC_EMAIL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "INVOICE_EMAIL")]
        public string INVOICE_EMAIL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PAPER_INVOICE")]
        public bool PAPER_INVOICE { get; set; }
        // navigationProperty

            /*
        /// <summary>
        /// 
        /// </summary>
        public virtual ESM_STATES ESM_STATES { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ESM_SKIN ESM_SKIN { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_USERGROUP> ESM_USERGROUP { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_USERGROUP> ESM_USERGROUP1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_PART_BUYER_GROUP_USER> ESM_PART_BUYER_GROUP_USER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_PROMOTIONAL_GIVEAWAY> ESM_PROMOTIONAL_GIVEAWAY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_SHIP_ESTIMATE> ESM_SHIP_ESTIMATE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_PROJECTS> ESM_PROJECTS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_PASS_HISTORY> ESM_PASS_HISTORY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_PASS_HISTORY> ESM_PASS_HISTORY1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_REPNEW_VIEWS> ESM_REPNEW_VIEWS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_CONSUMER> ESM_CONSUMER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_RET_STORE_SIGN_PACK> ESM_RET_STORE_SIGN_PACK { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_RET_VERSION_SIGNATURE_APPROVAL> ESM_RET_VERSION_SIGNATURE_APPROVAL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_RET_VERSION_SIGNATURE_APPROVAL> ESM_RET_VERSION_SIGNATURE_APPROVAL1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ASSET_ORDER> ASSET_ORDER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ASSET_ROLE ASSET_ROLE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_RET_APPROVAL_EMAIL> ESM_RET_APPROVAL_EMAIL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_RET_APPROVAL_EMAIL> ESM_RET_APPROVAL_EMAIL1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_RET_USER_MAP> ESM_RET_USER_MAP { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<SYS_TASK> SYS_TASK { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<SYS_TASK_ORDER_IMPORT> SYS_TASK_ORDER_IMPORT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_RET_VERSION> ESM_RET_VERSION { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_PURCHASE_ORDERS> ESM_PURCHASE_ORDERS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_LOGIN_AUDIT> ESM_LOGIN_AUDIT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_LOGIN_TOKEN> ESM_LOGIN_TOKEN { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_APPROVALS> ESM_APPROVALS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_PROJECT_REVISION_COMMENTS> ESM_PROJECT_REVISION_COMMENTS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_PROJECT_REVISIONS> ESM_PROJECT_REVISIONS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_PART_LIMIT> ESM_PART_LIMIT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_APPROVAL_ROUTING> ESM_APPROVAL_ROUTING { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_ACCOUNTING_UNIT_APPROVAL> ESM_ACCOUNTING_UNIT_APPROVAL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_HD_COMMENTS> ESM_HD_COMMENTS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_HD_TICKET_DETAIL> ESM_HD_TICKET_DETAIL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_HD_TICKET_DETAIL> ESM_HD_TICKET_DETAIL1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_HD_TICKET> ESM_HD_TICKET { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_HD_TICKET> ESM_HD_TICKET1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_HD_COMMENTS> ESM_HD_COMMENTS1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_REP_SLICE_USER> ESM_REP_SLICE_USER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_HIERARCHY> ESM_HIERARCHY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ESM_ACCOUNTING_UNIT ESM_ACCOUNTING_UNIT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_HIERARCHY> ESM_HIERARCHY1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_MSGUSER> ESM_MSGUSER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_MESSAGES> ESM_MESSAGES { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_MESSAGES> ESM_MESSAGES1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ASSET> ASSETs { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_CART> ESM_CART { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_CART_CUST_FIELDS> ESM_CART_CUST_FIELDS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_CART_QUICK> ESM_CART_QUICK { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_ASSET_UPLOAD> ESM_ASSET_UPLOAD { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_DASH> ESM_DASH { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_DASH_WIDGET_USER> ESM_DASH_WIDGET_USER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_IMPORT_PROCESSING> ESM_IMPORT_PROCESSING { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ESM_SITE ESM_SITE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_ASSET_LIST> ESM_ASSET_LIST { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ESM_COMP_USERGROUP ESM_COMP_USERGROUP { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_SOFT_PROOFING_TRANSACTION_LOG> ESM_SOFT_PROOFING_TRANSACTION_LOG { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_GLOBAL_FORMS_USERS> ESM_GLOBAL_FORMS_USERS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_PROMO_USERS_USERGROUP> ESM_PROMO_USERS_USERGROUP { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_COMP_USER_ADDRESS_MAP> ESM_COMP_USER_ADDRESS_MAP { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_CART_ADDRESS> ESM_CART_ADDRESS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ESM_COMP_USERGROUP ESM_COMP_USERGROUP1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_ACCOUNTING_UNIT_USER> ESM_ACCOUNTING_UNIT_USER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_COMP_USER_PAGES> ESM_COMP_USER_PAGES { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_FILE_DOWNLOAD_LOG> ESM_FILE_DOWNLOAD_LOG { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_MAILING_LIST> ESM_MAILING_LIST { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_COMP_USER_WORKFLOW> ESM_COMP_USER_WORKFLOW { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_TRIGGER_RULE_APPROVER> ESM_TRIGGER_RULE_APPROVER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_ORDER_APPROVER_WORKFLOW> ESM_ORDER_APPROVER_WORKFLOW { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_COMP_USER_DOLLAR> ESM_COMP_USER_DOLLAR { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_COMP_USER_PAYMENT_METHOD> ESM_COMP_USER_PAYMENT_METHOD { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_GLOBAL_FORMS_PROFILE> ESM_GLOBAL_FORMS_PROFILE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ESM_COMPANY ESM_COMPANY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_ORDERS> ESM_ORDERS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_USER_FILES> ESM_USER_FILES { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_REPNEW_VIEW_USERS> ESM_REPNEW_VIEW_USERS { get; set; }
        */
    }
}
