//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argosy.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArgosyEntities : DbContext
    {
        public ArgosyEntities()
            : base("name=ArgosyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUserPassword> AspNetUserPasswords { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ESM_COMP_USERGROUP> ESM_COMP_USERGROUP { get; set; }
        public virtual DbSet<ESM_COMP_USERS> ESM_COMP_USERS { get; set; }
        public virtual DbSet<ESM_COMPANY> ESM_COMPANY { get; set; }
        public virtual DbSet<ESM_COUNTRIES> ESM_COUNTRIES { get; set; }
        public virtual DbSet<ESM_GATEWAY_TYPE> ESM_GATEWAY_TYPE { get; set; }
        public virtual DbSet<ESM_GROUPS> ESM_GROUPS { get; set; }
        public virtual DbSet<ESM_HIERARCHY> ESM_HIERARCHY { get; set; }
        public virtual DbSet<ESM_LOGIN_AUDIT> ESM_LOGIN_AUDIT { get; set; }
        public virtual DbSet<ESM_LOGIN_TOKEN> ESM_LOGIN_TOKEN { get; set; }
        public virtual DbSet<ESM_ORDERS> ESM_ORDERS { get; set; }
        public virtual DbSet<ESM_PART> ESM_PART { get; set; }
        public virtual DbSet<ESM_PARTGROUP> ESM_PARTGROUP { get; set; }
        public virtual DbSet<ESM_PAYMENT_AUTH> ESM_PAYMENT_AUTH { get; set; }
        public virtual DbSet<ESM_SITE> ESM_SITE { get; set; }
        public virtual DbSet<ESM_SITE_GATEWAY> ESM_SITE_GATEWAY { get; set; }
        public virtual DbSet<ESM_SITE_GATEWAY_OPTION> ESM_SITE_GATEWAY_OPTION { get; set; }
        public virtual DbSet<ESM_STATES> ESM_STATES { get; set; }
        public virtual DbSet<ESM_TYPEAHEAD> ESM_TYPEAHEAD { get; set; }
        public virtual DbSet<ESM_UI_CUSTOM_TEXT> ESM_UI_CUSTOM_TEXT { get; set; }
        public virtual DbSet<ESM_USERGROUP> ESM_USERGROUP { get; set; }
        public virtual DbSet<ESM_USERS> ESM_USERS { get; set; }
        public virtual DbSet<ViewCompanyUserHierarchy> ViewCompanyUserHierarchies { get; set; }
    }
}
