//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argosy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESM_LOGIN_AUDIT
    {
        public int LOGIN_ID { get; set; }
        public Nullable<int> COMP_USER_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string IP_ADDRESS { get; set; }
        public string SERVER_NAME { get; set; }
        public string SESSION_ID { get; set; }
        public int FAILED_ATTEMPT_COUNT { get; set; }
        public bool FLAG_LOCKED_ACCOUNT { get; set; }
        public bool FLAG_LOGGED_IN { get; set; }
        public bool FLAG_RESET_PASSWORD { get; set; }
        public Nullable<System.DateTime> DATE_PASSWORD_RESET { get; set; }
        public Nullable<System.DateTime> DATE_LAST_LOGIN { get; set; }
        public Nullable<System.DateTime> DATE_LAST_LOGIN_ATTEMPT { get; set; }
        public System.DateTime DATEMODIFIED { get; set; }
    
        public virtual ESM_COMP_USERS ESM_COMP_USERS { get; set; }
        public virtual ESM_USERS ESM_USERS { get; set; }
    }
}
