//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argosy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESM_STATES
    {
        public int STATE_ID { get; set; }
        public int COUNTRY_ID { get; set; }
        public string STATE { get; set; }
        public string STATE_CODE { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public Nullable<int> CREATEDBY { get; set; }
        public Nullable<System.DateTime> DATEMODIFIED { get; set; }
        public Nullable<int> MODIFIEDBY { get; set; }
    
        public virtual ESM_COUNTRIES ESM_COUNTRIES { get; set; }
    }
}
