//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argosy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESM_COMP_USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESM_COMP_USERS()
        {
            this.ESM_HIERARCHY = new HashSet<ESM_HIERARCHY>();
            this.ESM_HIERARCHY1 = new HashSet<ESM_HIERARCHY>();
            this.ESM_LOGIN_AUDIT = new HashSet<ESM_LOGIN_AUDIT>();
            this.ESM_LOGIN_TOKEN = new HashSet<ESM_LOGIN_TOKEN>();
            this.ESM_ORDERS = new HashSet<ESM_ORDERS>();
            this.ESM_USERGROUP = new HashSet<ESM_USERGROUP>();
            this.ESM_USERGROUP1 = new HashSet<ESM_USERGROUP>();
        }
    
        public int COMP_USER_ID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public Nullable<int> ADDRESS_ID { get; set; }
        public Nullable<int> SITE_ID { get; set; }
        public Nullable<int> MULTIPLIER_ID { get; set; }
        public Nullable<int> DEFAULT_SKIN_ID { get; set; }
        public int STYLE_SHEET_ID { get; set; }
        public Nullable<int> THEME_ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string TITLE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> zPHONE { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY { get; set; }
        public Nullable<int> STATE { get; set; }
        public string COUNTRY { get; set; }
        public string ZIP { get; set; }
        public decimal SPENDING_LIMIT { get; set; }
        public string ACTIVE { get; set; }
        public string ADMIN_ACCESS { get; set; }
        public string PROJECT_REVISION_ACCESS { get; set; }
        public string POWER_BUYER { get; set; }
        public string EMAIL_DISTR { get; set; }
        public string PRINT_ORDERS { get; set; }
        public string BILLING_ACCESS { get; set; }
        public Nullable<int> DISCOUNT_LEVEL { get; set; }
        public decimal DISCOUNT_DOLLARS { get; set; }
        public Nullable<System.DateTime> REGISTER_DATE { get; set; }
        public string DEFAULT_LOGO { get; set; }
        public string DIVISION_NAME { get; set; }
        public string WEBSITE { get; set; }
        public Nullable<decimal> FAX { get; set; }
        public string CUSTOM01 { get; set; }
        public string CUSTOM02 { get; set; }
        public string CUSTOM03 { get; set; }
        public string EXT_IDENTIFIER { get; set; }
        public Nullable<int> USER_PROFILE_GROUP_ID { get; set; }
        public Nullable<int> COMP_USERGROUP_ID { get; set; }
        public string FLAG_RFQ_MODULE { get; set; }
        public bool FLAG_EMAIL_CREATE_MESSAGE { get; set; }
        public bool FLAG_EMAIL_ORDER_PLACED { get; set; }
        public bool FLAG_EMAIL_PROJECT_REVISION { get; set; }
        public bool FLAG_EMAIL_ORDER_SHIPPED { get; set; }
        public bool FLAG_EMAIL_INVENTORY_WARNING { get; set; }
        public bool FLAG_CONSUMER_MODULE { get; set; }
        public int FLAG_APPROVALS { get; set; }
        public string FLAG_AGREED_TO_USRAGR { get; set; }
        public bool FLAG_ALLOW_BULK_ORDER_PLACEMENT { get; set; }
        public bool IS_STORE { get; set; }
        public bool IS_RETAIL { get; set; }
        public bool EMAIL_SENT { get; set; }
        public Nullable<System.DateTime> USRAGR_DATE { get; set; }
        public string USRAGR_IP { get; set; }
        public string USRAGR_NAME { get; set; }
        public string USRAGR_COMPANY { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public int CREATEDBY { get; set; }
        public Nullable<System.DateTime> DATEMODIFIED { get; set; }
        public int MODIFIEDBY { get; set; }
        public Nullable<int> ACCOUNTING_UNIT_ID { get; set; }
        public string TITLE2 { get; set; }
        public string USER_PHOTO { get; set; }
        public string PHONE_NUMBER2 { get; set; }
        public string PHONE_NUMBER3 { get; set; }
        public Nullable<int> ASSET_ROLE_ID { get; set; }
        public System.Guid COMP_USER_GUID { get; set; }
        public Nullable<bool> IS_RETAIL_CONTRIBUTOR { get; set; }
        public string COMP_USER_HASH { get; set; }
        public string INCLUSION_TAGS { get; set; }
        public string EXCLUSION_TAGS { get; set; }
        public string EXTERNAL_ID { get; set; }
        public bool IS_SSO { get; set; }
        public Nullable<int> DYNAMIC_USERGROUP_ID { get; set; }
        public bool IS_GENERIC_USER { get; set; }
        public bool IS_PRICE_ADMIN { get; set; }
        public string CC_EMAIL { get; set; }
        public string INVOICE_EMAIL { get; set; }
        public bool PAPER_INVOICE { get; set; }
    
        public virtual ESM_COMPANY ESM_COMPANY { get; set; }
        public virtual ESM_SITE ESM_SITE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_HIERARCHY> ESM_HIERARCHY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_HIERARCHY> ESM_HIERARCHY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_LOGIN_AUDIT> ESM_LOGIN_AUDIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_LOGIN_TOKEN> ESM_LOGIN_TOKEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_ORDERS> ESM_ORDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_USERGROUP> ESM_USERGROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_USERGROUP> ESM_USERGROUP1 { get; set; }
    }
}
