//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argosy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESM_PART
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESM_PART()
        {
            this.ESM_PARTGROUP = new HashSet<ESM_PARTGROUP>();
            this.ESM_UI_CUSTOM_TEXT = new HashSet<ESM_UI_CUSTOM_TEXT>();
        }
    
        public int PART_ID { get; set; }
        public int SITE_ID { get; set; }
        public int COMPANY_ID { get; set; }
        public Nullable<int> VENDOR_ID { get; set; }
        public Nullable<int> CF_PART_ID { get; set; }
        public Nullable<int> ALIAS_PARENT_PART_ID { get; set; }
        public Nullable<int> SOFTPROOF_PROJECT_ID { get; set; }
        public Nullable<int> PART_BUYER_GROUP_ID { get; set; }
        public string DISPLAY_SKU { get; set; }
        public string PART_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string LONG_DESCRIPTION { get; set; }
        public int PIECES { get; set; }
        public decimal QTY_AVAIL { get; set; }
        public decimal QTY_ONHAND { get; set; }
        public Nullable<int> QTY_INPRODUCTION { get; set; }
        public decimal WEIGHT { get; set; }
        public decimal CPQ { get; set; }
        public string ORDER_UNIT { get; set; }
        public string PRINT_FILE_NAME { get; set; }
        public string FILENAME { get; set; }
        public string TN_FILENAME { get; set; }
        public string GI_FILENAME { get; set; }
        public decimal UNIT_PRICE { get; set; }
        public decimal UNIT_COST { get; set; }
        public decimal MIN_QTY { get; set; }
        public decimal MIN_QTY2 { get; set; }
        public decimal MAX_QTY { get; set; }
        public int MAX_ORDER_QTY { get; set; }
        public Nullable<int> APPROVAL_THRESHOLD_QUANTITY { get; set; }
        public int PART_LEAD_TIME { get; set; }
        public int DEPLETE_CHILD { get; set; }
        public System.DateTime AVAIL_DATE { get; set; }
        public System.DateTime EXPIRATION_DATE { get; set; }
        public string COMMENTS { get; set; }
        public string VENDOR_SKU { get; set; }
        public string CLIENT_CODE { get; set; }
        public string INTERNAL_PART_ID { get; set; }
        public string FORM_NUM { get; set; }
        public string SHORT_CODE { get; set; }
        public string COMMOD_CODE { get; set; }
        public string ITEM_TYPE { get; set; }
        public string MANUFACTURER { get; set; }
        public string PLANT { get; set; }
        public string KIT_TYPE { get; set; }
        public string KIT_INSTR { get; set; }
        public string ACTIVE { get; set; }
        public string FLAG_CUSTOMIZE { get; set; }
        public string FLAG_PREVIEW { get; set; }
        public string FLAG_OFFERED { get; set; }
        public Nullable<bool> FLAG_PO_REQUIRED { get; set; }
        public string FLAG_KIT { get; set; }
        public bool FLAG_EXPIRE_PART { get; set; }
        public bool FLAG_IS_CUSTOMER_OWNED { get; set; }
        public string FEATURED_ITEM { get; set; }
        public bool ALLOW_UPLOAD { get; set; }
        public string FLAG_ALIASED { get; set; }
        public bool DIRECT_MAIL_ALLOWED { get; set; }
        public bool IS_RETAIL { get; set; }
        public bool IS_SERVICE_CHARGE_PART { get; set; }
        public bool IS_PRINT_WORK_FLOW { get; set; }
        public bool HAS_SERIAL_NUMBER { get; set; }
        public bool IS_FEATURED_PART { get; set; }
        public int MIN_ORDER_QTY { get; set; }
        public bool IS_LIMIT_PART_ORDERING_QTY { get; set; }
        public string CUSTOM01 { get; set; }
        public string CUSTOM02 { get; set; }
        public string CUSTOM03 { get; set; }
        public string CUSTOM04 { get; set; }
        public string CUSTOM05 { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
        public System.DateTime DATECREATED { get; set; }
        public int CREATEDBY { get; set; }
        public System.DateTime DATEMODIFIED { get; set; }
        public int MODIFIEDBY { get; set; }
        public Nullable<int> PART_PRICE_AGGREGATE_ID { get; set; }
        public bool ALLOW_LIST { get; set; }
        public bool IS_MAILING_LIST { get; set; }
        public bool ALLOW_LIST_PURCHASE { get; set; }
        public bool LIST_IS_REQUIRED { get; set; }
        public bool UPLOAD_IS_REQUIRED { get; set; }
        public string FLAG_DELIVERY { get; set; }
        public string DESIGN_XML { get; set; }
        public string PRINT_SPECS { get; set; }
        public bool IS_LOT_NUMBER_REQUIRED { get; set; }
        public int FINISHED_DOCUMENT_NUMBER_OF_PAGES { get; set; }
        public decimal FINISHED_TRIM_WIDTH { get; set; }
        public decimal FINISHED_TRIM_HEIGHT { get; set; }
        public bool NO_PO_REQUIRED { get; set; }
        public Nullable<bool> FLAG_GRID_VIEW_CONFIGURATION { get; set; }
        public Nullable<int> GLOBAL_FORMS_PROFILE_ID { get; set; }
        public Nullable<int> RET_SIGN_PACK_ID { get; set; }
        public Nullable<int> DAYS_OF_STOCK_MIN { get; set; }
        public bool FLAG_SHOW_HIGH_RES_PROOF { get; set; }
        public Nullable<int> CUSTOMIZATION_TEMPLATE_ID { get; set; }
        public int NUMBER_OF_SERIALS { get; set; }
        public bool IS_PURCHASE_WORKFLOW { get; set; }
        public Nullable<int> PRODUCTION_QUEUE_ID { get; set; }
        public Nullable<int> PAPER_STOCK_ID { get; set; }
        public string KEYWORDS { get; set; }
        public Nullable<int> LOCK_ORDER_QTY { get; set; }
        public string LG_FILENAME { get; set; }
        public Nullable<int> GLOBAL_FORMS_ID { get; set; }
        public string OVERRIDE_FILENAME { get; set; }
        public Nullable<System.DateTime> DATE_REVISED { get; set; }
        public string INCLUSION_TAGS { get; set; }
        public string EXCLUSION_TAGS { get; set; }
        public bool IS_DELETED { get; set; }
        public string COMMENTS_ADMIN { get; set; }
        public string PERSONALIZATION_COMMENTS { get; set; }
        public Nullable<bool> PS_DUPLEX { get; set; }
        public Nullable<decimal> PS_BLEED { get; set; }
        public string PS_FOLDS { get; set; }
        public Nullable<int> SITE_SHIPMENT_GROUP_ID { get; set; }
        public Nullable<int> BOX_SIZE_ID { get; set; }
        public string SECONDARY_NAME { get; set; }
        public string CALL_TO_ACTION { get; set; }
        public Nullable<int> SITE_UNIT_OF_MEASURE_ID { get; set; }
    
        public virtual ESM_COMPANY ESM_COMPANY { get; set; }
        public virtual ESM_SITE ESM_SITE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_PARTGROUP> ESM_PARTGROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_UI_CUSTOM_TEXT> ESM_UI_CUSTOM_TEXT { get; set; }
    }
}
