//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argosy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESM_LOGIN_TOKEN
    {
        public int LOGIN_TOKEN_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> COMP_USER_ID { get; set; }
        public string REQUEST_IP { get; set; }
        public string AUTH_TOKEN { get; set; }
        public System.DateTime DATEEXPIRES { get; set; }
        public string AUTHORIZED_PAGE { get; set; }
        public System.DateTime DATECREATED { get; set; }
        public int CREATEDBY { get; set; }
        public bool FLAG_TOKEN_USED { get; set; }
    
        public virtual ESM_COMP_USERS ESM_COMP_USERS { get; set; }
        public virtual ESM_USERS ESM_USERS { get; set; }
    }
}
