//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argosy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESM_SITE_GATEWAY_OPTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESM_SITE_GATEWAY_OPTION()
        {
            this.ESM_SITE_GATEWAY = new HashSet<ESM_SITE_GATEWAY>();
        }
    
        public int SITE_GATEWAY_OPTION_ID { get; set; }
        public bool FLAG_SUPPORTS_PURCHASE { get; set; }
        public bool FLAG_SUPPORTS_AUTHROIZE { get; set; }
        public bool FLAG_SUPPORTS_CAPTURE { get; set; }
        public bool FLAG_SUPPORTS_CREDITS { get; set; }
        public bool FLAG_SUPPORTS_GENERAL_CREDIT { get; set; }
        public bool FLAG_SUPPORTS_VOID { get; set; }
        public bool FLAG_SUPPORTS_VERIFY { get; set; }
        public bool FLAG_SUPPORTS_REFERENCE_PURCHASE { get; set; }
        public bool FLAG_SUPPORTS_PURCHASE_VIA_PREAUTH { get; set; }
        public bool FLAG_SUPPORTS_OFFSITE_PURCHASE { get; set; }
        public bool FLAG_SUPPORTS_OFFSITE_AUTHORIZE { get; set; }
        public bool FLAG_SUPPORTS_3DSECURE_PURCHASE { get; set; }
        public bool FLAG_SUPPORTS_3DSECURE_AUTHORIZE { get; set; }
        public bool FLAG_SUPPORTS_STORE { get; set; }
        public bool FLAG_SUPPORTS_REMOVE { get; set; }
        public bool FLAG_SUPPORTS_FRAUD_REVIEW { get; set; }
        public bool FLAG_SUPPORTS_REFERENCE_AUTHORIZATION { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
        public System.DateTime DATE_UPDATED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_SITE_GATEWAY> ESM_SITE_GATEWAY { get; set; }
    }
}
