//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argosy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESM_ORDERS
    {
        public int ORDER_ID { get; set; }
        public int COMP_USER_ID { get; set; }
        public int COMPANY_ID { get; set; }
        public int SITE_ID { get; set; }
        public int TYPE_ID { get; set; }
        public string STATUS_ID { get; set; }
        public int CARRIER_ID { get; set; }
        public Nullable<int> CONSOLIDATE_ID { get; set; }
        public Nullable<int> RETAIL_PROJ_ID { get; set; }
        public Nullable<int> ACCOUNTING_UNIT_ID { get; set; }
        public string ORDER_DISP_NO { get; set; }
        public string PO_NUM { get; set; }
        public System.DateTime ORDER_DATE { get; set; }
        public Nullable<System.DateTime> CLOSE_DATE { get; set; }
        public Nullable<System.DateTime> PICK_DATE { get; set; }
        public System.DateTime DESIRED_SHIP_DATE { get; set; }
        public System.DateTime INVOICE_DATE { get; set; }
        public string CREDIT_CARD_INFO { get; set; }
        public string COMMENTS { get; set; }
        public bool EXPEDITE { get; set; }
        public string PRICE_TYPE { get; set; }
        public Nullable<int> CZ { get; set; }
        public Nullable<int> PICKER { get; set; }
        public decimal EST_SHIPPING_COSTS { get; set; }
        public decimal FULFILL_ORDER_COST { get; set; }
        public decimal FULFILL_LINE_COST { get; set; }
        public decimal FULFILL_EACH_COST { get; set; }
        public decimal LIST_COST { get; set; }
        public decimal DISCOUNT { get; set; }
        public decimal SALES_TAX_CHARGES { get; set; }
        public string THIRD_PARTY_ACCOUNT_NUMBER { get; set; }
        public int INVOICE_STATUS { get; set; }
        public Nullable<int> CONSUMER_ID { get; set; }
        public bool PAYMENT_IS_COMPLETE { get; set; }
        public bool IS_INCOMPLETE_ORDER { get; set; }
        public bool EMAIL_SENT { get; set; }
        public Nullable<bool> FLAG_CONSOLIDATED { get; set; }
        public Nullable<bool> FLAG_ALLOW_PARTIAL_SHIP { get; set; }
        public bool FLAG_ALLOW_CONSOLIDATE_ORDERS { get; set; }
        public Nullable<bool> FLAG_REQUIRE_CARTONS { get; set; }
        public bool IS_FREIGHT_ONLY_BILLING { get; set; }
        public bool IS_PAID_IN_FULL_AT_TIME_OF_ORDER { get; set; }
        public string FLAG_PAYMENT { get; set; }
        public bool FAST_PICKPACK { get; set; }
        public bool FLAG_REQUIRE_SIGNATURE { get; set; }
        public string APPROVAL_WORK_FLOW_TYPE { get; set; }
        public bool EXEMPT_SHIPPING_AND_HANDLING { get; set; }
        public bool SHIPPING_AND_HANDLING_PAID_BY_THIRD_PARTY { get; set; }
        public string CUSTOM01 { get; set; }
        public string CUSTOM02 { get; set; }
        public string CUSTOM03 { get; set; }
        public string CUSTOM04 { get; set; }
        public string CUSTOM05 { get; set; }
        public System.DateTime DATECREATED { get; set; }
        public int CREATEDBY { get; set; }
        public System.DateTime DATEMODIFIED { get; set; }
        public int MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> APPROVE_DENY_DATE { get; set; }
        public Nullable<int> WAREHOUSE_ID { get; set; }
        public string PROMO_CODE { get; set; }
        public Nullable<decimal> PROMO_CODE_DISCOUNT { get; set; }
        public System.DateTime DESIRE_PROD_DATE { get; set; }
        public string APPROVAL_PENDING_REASON { get; set; }
        public string ORDER_TAG { get; set; }
        public decimal ORDER_WEIGHT { get; set; }
        public System.Guid ORDER_GUID { get; set; }
        public bool IS_TRANSMITTED { get; set; }
        public string APPROVAL_SUMMARY { get; set; }
        public string CURRANCY_CODE { get; set; }
        public string LANGUAGE_CULTURE { get; set; }
        public string CURRENCY_CODE { get; set; }
        public string SHIPPING_ESTIMATE_CALC_JSON { get; set; }
        public Nullable<decimal> INVOICE_FEE { get; set; }
        public bool MAIL_INVOICE { get; set; }
        public string INVOICE_EMAIL { get; set; }
    
        public virtual ESM_COMP_USERS ESM_COMP_USERS { get; set; }
        public virtual ESM_COMPANY ESM_COMPANY { get; set; }
        public virtual ESM_SITE ESM_SITE { get; set; }
    }
}
