//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argosy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESM_SITE_GATEWAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESM_SITE_GATEWAY()
        {
            this.ESM_COMPANY = new HashSet<ESM_COMPANY>();
        }
    
        public int SITE_GATEWAY_ID { get; set; }
        public int SITE_ID { get; set; }
        public int GATEWAY_TYPE_ID { get; set; }
        public int SITE_GATEWAY_OPTION_ID { get; set; }
        public string GATEWAY_TOKEN { get; set; }
        public string GATEWAY_NAME { get; set; }
        public string GATEWAY_DESCRIPTION { get; set; }
        public string GATEWAY_CREATE_RESPONSE { get; set; }
        public bool FLAG_TEST_MODE { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
        public System.DateTime DATE_UPDATED { get; set; }
        public string DISPLAY_NAME { get; set; }
        public bool IS_DEFAULT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_COMPANY> ESM_COMPANY { get; set; }
        public virtual ESM_GATEWAY_TYPE ESM_GATEWAY_TYPE { get; set; }
        public virtual ESM_SITE ESM_SITE { get; set; }
        public virtual ESM_SITE_GATEWAY_OPTION ESM_SITE_GATEWAY_OPTION { get; set; }
    }
}
