//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argosy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESM_COMP_USERGROUP
    {
        public int COMP_USERGROUP_ID { get; set; }
        public int COMP_ID { get; set; }
        public Nullable<int> ASSET_ROLE_ID { get; set; }
        public string GROUP_NAME { get; set; }
        public string GROUP_DESCRIPTION { get; set; }
        public Nullable<decimal> MAXORDERAMOUNT { get; set; }
        public decimal DIRECT_MAIL_SPENDING_MINIMUM { get; set; }
        public string ORDER_NUMBER_SUFIX { get; set; }
        public string ORDER_NUMBER_PREFIX { get; set; }
        public string CYCLE { get; set; }
        public Nullable<int> WAREHOUSE_ID { get; set; }
        public string LANDING_PAGE_SETTING { get; set; }
        public string ORDERUNITS { get; set; }
        public string ORDERSTATUS { get; set; }
        public string ORDERAPPROVAL { get; set; }
        public Nullable<bool> CHANGESHIPADDRESSTO { get; set; }
        public Nullable<bool> DESIREDSHIPDATE { get; set; }
        public Nullable<bool> CHANGESHIPVIA { get; set; }
        public Nullable<bool> SHOWPRICE { get; set; }
        public Nullable<bool> ENFORCEORDERQTY { get; set; }
        public Nullable<bool> SHOWNEWPRODUCTGROUP { get; set; }
        public Nullable<bool> SHIPPINGCOST { get; set; }
        public Nullable<bool> ESTIMATEDSHIPPINGDATE { get; set; }
        public Nullable<bool> SHOWINVENTORY { get; set; }
        public Nullable<bool> SHOWPARTTHUMBNAIL { get; set; }
        public string BROWSEDISPLAY { get; set; }
        public Nullable<bool> CAPTURECREDITCARD { get; set; }
        public Nullable<bool> USEPRECLOSESTATUS { get; set; }
        public Nullable<bool> CREDITCARDPROCESS { get; set; }
        public Nullable<int> PRICELISTID { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<bool> FLAG_CONSUMER_MODULE { get; set; }
        public Nullable<bool> FLAG_EMAIL_CREATE_MESSAGE { get; set; }
        public Nullable<bool> FLAG_EMAIL_ORDER_PLACED { get; set; }
        public Nullable<bool> FLAG_EMAIL_ORDER_SHIPPED { get; set; }
        public Nullable<bool> FLAG_EMAIL_INVENTORY_WARNING { get; set; }
        public Nullable<bool> FLAG_EMAIL_PROJECT_REVISION { get; set; }
        public Nullable<bool> FLAG_ALLOW_LIST_PURCHASES { get; set; }
        public Nullable<bool> FLAG_ALLOW_EXISTING_LIST { get; set; }
        public Nullable<bool> FLAG_ALLOW_BUILD_LIST { get; set; }
        public Nullable<bool> FLAG_ALLOW_UPLOAD_LIST { get; set; }
        public Nullable<bool> FLAG_SHOW_CORPORATE_LIST { get; set; }
        public bool FLAG_ALLOW_MULTI_PRICE_LIST { get; set; }
        public bool FLAG_ALLOW_PROMO_CODES { get; set; }
        public bool PAYMENT_CREDIT_CARD_IS_ALLOWED { get; set; }
        public bool PAYMENT_ECHECK_IS_ALLOWED { get; set; }
        public bool PAYMENT_PO_IS_ALLOWED { get; set; }
        public bool PAYMENT_BILL_LATER_IS_ALLOWED { get; set; }
        public bool IS_RETAIL { get; set; }
        public bool IS_TAXABLE { get; set; }
        public bool FLAG_ASSET_RESTRICTED { get; set; }
        public bool IS_FREIGHT_ONLY_BILLING { get; set; }
        public string FLAG_INCLUDE_CUSTOM_FIELDS { get; set; }
        public string SHIPPING_DAY { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public Nullable<int> CREATEDBY { get; set; }
        public Nullable<System.DateTime> DATEMODIFIED { get; set; }
        public Nullable<int> MODIFIEDBY { get; set; }
        public Nullable<bool> SHOWPARTCATEGORYTHUMBNAIL { get; set; }
        public bool FLAG_ALLOW_EDIT_PRICE { get; set; }
        public bool FLAG_IS_SYSTEM_DOLLAR { get; set; }
        public string FLAG_STOP_ORDERS { get; set; }
        public bool FLAG_SHOW_CROSS_SALE { get; set; }
        public bool FLAG_APPROVAL_ON_ALL_ORDERS { get; set; }
        public bool FLAG_APPROVAL_ON_AU { get; set; }
        public bool FLAG_APPROVAL_ON_PART_THRESHHOLD { get; set; }
        public bool FLAG_APPROVAL_ON_SPENDING_LIMIT { get; set; }
        public Nullable<bool> FLAG_BYPASS_APPROVAL_ON_CC { get; set; }
        public string FLAG_APPROVAL_WORK_FLOW_TYPE { get; set; }
        public string MANAGE_BUDGET_LEVEL_SETTING { get; set; }
        public string TIME_INTERVAL { get; set; }
        public Nullable<int> GROUP_MANAGER_ID { get; set; }
        public Nullable<int> USER_GROUP_BUDGET { get; set; }
        public int FLAG_SALES_TAX_TYPE { get; set; }
        public Nullable<decimal> FLAT_SALES_TAX_RATE { get; set; }
        public Nullable<int> THEME_ID { get; set; }
        public bool FLAG_APPROVAL_OVERRIDE_PART_LIMIT { get; set; }
        public bool FLAG_APPROVAL_ON_ORDERS_PER_DAY { get; set; }
        public string INCLUSION_TAGS { get; set; }
        public string EXCLUSION_TAGS { get; set; }
        public bool IS_PUBLIC { get; set; }
        public bool FLAG_LOCK_ADDRESS { get; set; }
        public bool IS_DYNAMIC_GROUP { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string DISPLAY_IMAGE { get; set; }
        public bool PAYMENT_CO_OP_ONLY { get; set; }
        public bool FLAG_LOCK_ADDRESS_BT { get; set; }
        public string COMPANY_LOGO { get; set; }
    
        public virtual ESM_COMPANY ESM_COMPANY { get; set; }
    }
}
