//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argosy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESM_USERGROUP
    {
        public int USERGROUP_ID { get; set; }
        public int COMP_USER_ID { get; set; }
        public int GROUP_ID { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public Nullable<int> CREATEDBY { get; set; }
        public Nullable<System.DateTime> DATEMODIFIED { get; set; }
        public Nullable<int> MODIFIEDBY { get; set; }
    
        public virtual ESM_COMP_USERS ESM_COMP_USERS { get; set; }
        public virtual ESM_COMP_USERS ESM_COMP_USERS1 { get; set; }
        public virtual ESM_GROUPS ESM_GROUPS { get; set; }
    }
}
