//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argosy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESM_TYPEAHEAD
    {
        public int ID { get; set; }
        public int SITE_ID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public int TYPEAHEAD_TYPE_ID { get; set; }
        public string WORDS { get; set; }
    }
}
