//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argosy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESM_USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESM_USERS()
        {
            this.ESM_LOGIN_AUDIT = new HashSet<ESM_LOGIN_AUDIT>();
            this.ESM_LOGIN_TOKEN = new HashSet<ESM_LOGIN_TOKEN>();
        }
    
        public int USER_ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string EMAIL { get; set; }
        public string ACTIVE { get; set; }
        public string EMAIL_DISTR { get; set; }
        public Nullable<int> SITE_ID { get; set; }
        public string FLAG_BACKEND_ADMIN { get; set; }
        public string FLAG_SHIPPER_ONLY { get; set; }
        public string FLAG_WMS_ONLY { get; set; }
        public string FLAG_WMS_ADMIN { get; set; }
        public string FLAG_VIEW_CC { get; set; }
        public string CERQA_ADMIN { get; set; }
        public string FLAG_RFQ_MODULE { get; set; }
        public System.DateTime DATECREATED { get; set; }
        public int CREATEDBY { get; set; }
        public System.DateTime DATEMODIFIED { get; set; }
        public int MODIFIEDBY { get; set; }
        public bool FLAG_EMAIL_CREATE_MESSAGE { get; set; }
        public bool FLAG_EMAIL_ORDER_PLACED { get; set; }
        public bool FLAG_EMAIL_ORDER_SHIPPED { get; set; }
        public bool FLAG_EMAIL_INVENTORY_WARNING { get; set; }
        public bool FLAG_EMAIL_PROOF_RELATED { get; set; }
        public string FLAG_LICENSING_EDIT { get; set; }
        public string FLAG_REPORTS_ADD { get; set; }
        public bool FLAG_HD_ACCESS { get; set; }
        public bool FLAG_BILLING_ADMIN { get; set; }
        public Nullable<System.DateTime> DATE_AGREE_SA { get; set; }
        public Nullable<System.DateTime> DATE_AGREE_TU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_LOGIN_AUDIT> ESM_LOGIN_AUDIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_LOGIN_TOKEN> ESM_LOGIN_TOKEN { get; set; }
        public virtual ESM_SITE ESM_SITE { get; set; }
    }
}
