//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argosy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESM_SITE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESM_SITE()
        {
            this.ESM_COMP_USERS = new HashSet<ESM_COMP_USERS>();
            this.ESM_COMPANY = new HashSet<ESM_COMPANY>();
            this.ESM_ORDERS = new HashSet<ESM_ORDERS>();
            this.ESM_PART = new HashSet<ESM_PART>();
            this.ESM_PAYMENT_AUTH = new HashSet<ESM_PAYMENT_AUTH>();
            this.ESM_SITE_GATEWAY = new HashSet<ESM_SITE_GATEWAY>();
            this.ESM_USERS = new HashSet<ESM_USERS>();
        }
    
        public int SITE_ID { get; set; }
        public Nullable<int> MP_ID { get; set; }
        public Nullable<int> PAYMENT_GATEWAY_ID { get; set; }
        public string SITE_COMPANY { get; set; }
        public string CC_SITENAME { get; set; }
        public string IMG_FILENAME { get; set; }
        public string UPLOAD_DIR { get; set; }
        public string REPORT_CODE { get; set; }
        public string FLAG_ARGOSY_WMS { get; set; }
        public bool FLAG_ADDRESS_VERIFICATION { get; set; }
        public string SHIP_FROM_CONTACT { get; set; }
        public string SHIP_FROM_ADDRESS1 { get; set; }
        public string SHIP_FROM_ADDRESS2 { get; set; }
        public string SHIP_FROM_CITY { get; set; }
        public Nullable<int> SHIP_FROM_STATE { get; set; }
        public string SHIP_FROM_ZIP { get; set; }
        public string SHIP_FROM_COUNTRY { get; set; }
        public string SHIP_FROM_PHONE { get; set; }
        public string SHIP_FROM_FAX { get; set; }
        public string MINMAX_EMAIL { get; set; }
        public string VS_USER { get; set; }
        public string VS_PARTNER { get; set; }
        public string VS_VENDOR { get; set; }
        public string VS_PWD { get; set; }
        public bool VS_LIVE_SERVER { get; set; }
        public string FLAG_RFQ_MODULE { get; set; }
        public string VIRTUAL_DIRECTORY { get; set; }
        public string AMTREX_LOGIN { get; set; }
        public System.DateTime DATECREATED { get; set; }
        public int CREATEDBY { get; set; }
        public System.DateTime DATEMODIFIED { get; set; }
        public int MODIFIEDBY { get; set; }
        public Nullable<int> ORDER_MID_NUM { get; set; }
        public string PHONE { get; set; }
        public int VERSION { get; set; }
        public string SOFTPROOFING_FTP_SITE { get; set; }
        public string BATCH_PROCESSING_FOLDER { get; set; }
        public bool FLAT_RATE_CARRIER { get; set; }
        public string SITE_CC_CHARGE_NAME { get; set; }
        public Nullable<double> INSTATE_TAX_RATE { get; set; }
        public bool IS_ACTIVE { get; set; }
        public Nullable<int> BATCH_SITE_CONNECTOR_ID { get; set; }
        public string SITE_URL { get; set; }
        public string SITE_LABEL { get; set; }
        public string SITE_SQUARE_LOGO { get; set; }
        public System.Guid GUID { get; set; }
        public string FAVORITE_ICON_FILE { get; set; }
        public string LOADING_IMAGE_FILE { get; set; }
        public bool FLAG_ALLOW_COMPANY_WHITE_LABEL { get; set; }
        public bool FLAG_TRACK_INVENTORY_COST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_COMP_USERS> ESM_COMP_USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_COMPANY> ESM_COMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_ORDERS> ESM_ORDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_PART> ESM_PART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_PAYMENT_AUTH> ESM_PAYMENT_AUTH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_SITE_GATEWAY> ESM_SITE_GATEWAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_USERS> ESM_USERS { get; set; }
    }
}
