//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argosy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESM_PARTGROUP
    {
        public int PARTGROUP_ID { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public int PART_ID { get; set; }
        public Nullable<int> ORDER_TEMPLATE_COLUMN_NUMBER { get; set; }
        public Nullable<int> ORDER_TEMPLATE_BOX_NUMBER { get; set; }
        public Nullable<int> ORDER_TEMPLATE_ITEM_RANK { get; set; }
        public short PART_RANKING { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public Nullable<int> CREATEDBY { get; set; }
        public Nullable<System.DateTime> DATEMODIFIED { get; set; }
        public Nullable<int> MODIFIEDBY { get; set; }
    
        public virtual ESM_GROUPS ESM_GROUPS { get; set; }
        public virtual ESM_PART ESM_PART { get; set; }
    }
}
