//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argosy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESM_GROUPS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESM_GROUPS()
        {
            this.ESM_USERGROUP = new HashSet<ESM_USERGROUP>();
            this.ESM_PARTGROUP = new HashSet<ESM_PARTGROUP>();
        }
    
        public int GROUP_ID { get; set; }
        public int PARENT_GROUP_ID { get; set; }
        public string GROUP_NAME { get; set; }
        public string GROUP_DESCRIP { get; set; }
        public string LONG_DESCRIPTION { get; set; }
        public string IMAGE_NAME { get; set; }
        public short GROUP_RANKING { get; set; }
        public string ACTIVE { get; set; }
        public string PRIVATE { get; set; }
        public Nullable<int> IS_ORDER_TEMPLATE { get; set; }
        public bool IS_DEFAULT_OPEN { get; set; }
        public bool IS_GRAPHICAL_INTERFACE { get; set; }
        public bool IS_DISTRIBUTION_PUSH { get; set; }
        public Nullable<System.DateTime> AVAIL_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRE_DATE { get; set; }
        public Nullable<System.DateTime> EST_SHIP_DATE { get; set; }
        public Nullable<System.DateTime> PRINT_DATE { get; set; }
        public Nullable<System.DateTime> LAST_ORDER_DATE { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public Nullable<int> CREATEDBY { get; set; }
        public Nullable<System.DateTime> DATEMODIFIED { get; set; }
        public Nullable<int> MODIFIEDBY { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<int> COMPANY_PAGE_ID { get; set; }
        public bool FLAG_HIDE_FROM_CATALOG_MENU { get; set; }
        public string COMPANY_LOGO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_USERGROUP> ESM_USERGROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESM_PARTGROUP> ESM_PARTGROUP { get; set; }
    }
}
